import { test,expect } from '@playwright/test';
import JSZip from 'jszip';
import { pngBuffer,wavBuffer,webmBuffer } from './media-fixtures';

test('ZIP backup contains every table and restores IndexedDB plus OPFS',async({page})=>{
  test.setTimeout(90_000);await page.goto('./#/capture');await page.getByLabel('记录标题').fill('备份恢复验收');await page.getByLabel('记录内容').fill('这条记录和图片必须一起回来');
  const input=page.locator('input[type=file]');await input.setInputFiles({name:'backup.png',mimeType:'image/png',buffer:pngBuffer});await expect(page.locator('.media-previews>div')).toHaveCount(1);await input.setInputFiles({name:'backup.webm',mimeType:'video/webm',buffer:await webmBuffer(page)});await expect(page.locator('.media-previews>div')).toHaveCount(2);await input.setInputFiles({name:'backup.wav',mimeType:'audio/wav',buffer:wavBuffer()});await expect(page.locator('.media-previews>div')).toHaveCount(3);await page.getByRole('button',{name:'完成'}).click();await expect(page.getByRole('heading',{name:'备份恢复验收'})).toBeVisible();
  await page.goto('./#/profile');await page.getByRole('button',{name:/备份与恢复/}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:/导出完整 ZIP/}).click();const download=await downloadPromise,path=await download.path();expect(path).toBeTruthy();
  const zip=await JSZip.loadAsync(await (await import('node:fs/promises')).readFile(path!));expect(zip.file('manifest.json')).toBeTruthy();expect(zip.file('data.json')).toBeTruthy();expect(Object.keys(zip.files).some(name=>name.startsWith('media/images/'))).toBeTruthy();expect(Object.keys(zip.files).some(name=>name.startsWith('media/videos/'))).toBeTruthy();expect(Object.keys(zip.files).some(name=>name.startsWith('media/audio/'))).toBeTruthy();expect(Object.keys(zip.files).some(name=>name.startsWith('media/thumbnails/'))).toBeTruthy();
  const data=JSON.parse(await zip.file('data.json')!.async('string'));for(const key of ['lines','goals','entries','metrics','tags','templates','media','knowledgeNodes','knowledgeLinks','emotions','timelineEvents','settings'])expect(Array.isArray(data[key])).toBeTruthy();
  await page.getByRole('button',{name:'关闭'}).click();await page.evaluate(async()=>{const database=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('MYMDatabase');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});const stores=Array.from(database.objectStoreNames);await new Promise<void>((resolve,reject)=>{const tx=database.transaction(stores,'readwrite');for(const store of stores)tx.objectStore(store).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});database.close();const root=await navigator.storage.getDirectory();await root.removeEntry('MYM',{recursive:true}).catch(()=>undefined);});
  await page.reload();await page.getByRole('button',{name:/备份与恢复/}).click();await page.locator('.dialog-sheet input[type=file]').setInputFiles(path!);await expect(page.getByText(/1 条记录/)).toBeVisible();await page.getByRole('button',{name:'确认恢复'}).click();await expect(page.getByText('备份已完整恢复')).toBeVisible();
  await page.goto('./#/timeline');await page.getByText('备份恢复验收').click();await expect(page.getByRole('heading',{name:'备份恢复验收'})).toBeVisible();await expect(page.locator('.note-media-strip img.full-media')).toBeVisible();await expect(page.locator('.note-media-strip video')).toBeVisible();await expect(page.locator('.note-media-strip audio')).toBeVisible();
});
