import { useEffect, useMemo, useRef, useState, type ChangeEvent, type PointerEvent as ReactPointerEvent, type ReactNode, type WheelEvent } from 'react';
import { Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import {
  ArrowDown, ArrowLeft, ArrowUp, BarChart3, BookOpen, BriefcaseBusiness, Check, ChevronRight, CircleDot, Clock3, Database,
  Ellipsis, FileText, HardDrive, Home as HomeIcon, Image as ImageIcon, Lightbulb, ListTodo, Mic, MoreHorizontal, Notebook,
  Paperclip, Play, Plus, RefreshCw, Search, Settings, Share2, Sparkles, Tag as TagIcon, Trash2, UserRound, Users, Video,
  X, ZoomIn, ZoomOut
} from 'lucide-react';
import { db, clearExampleData, ensureSeedData, ensureVisualFixtures } from './data/db';
import { importMediaFile, cleanOrphanMedia, deleteMediaRecordIfUnreferenced, findOrphanMedia } from './data/media';
import { selectPrimaryMedia, toEntryPresentation } from './data/presentation';
import { deleteTag, ensureTags, mergeTags, normalizeTag, recalculateTagCounts, renameTag } from './data/tags';
import { createBackupZip, downloadBlob, inspectBackupZip, restoreBackupZip, type BackupSummary } from './data/backup';
import { formatBytes, requestPersistentStorage } from './data/storage';
import { Dialog, Toast } from './components/Dialog';
import { FullMedia, MediaThumbnail } from './components/LocalMedia';
import type { Entry, Goal, Line, Media, StorageStatus, Tag, Template, TemplateField, TemplateFieldType, TemplateFieldValue } from './types';

const asset=(path:string)=>`${import.meta.env.BASE_URL}${path.replace(/^\//,'')}`;
const refs:Record<string,string>={home:asset('design-reference/01_home.png'),fitness:asset('design-reference/02_fitness.png'),cpa:asset('design-reference/03_cpa.png'),knowledge:asset('design-reference/04_knowledge.png'),timeline:asset('design-reference/05_timeline.png'),capture:asset('design-reference/06_quick_capture.png'),goals:asset('design-reference/07_goals.png'),note:asset('design-reference/08_note_detail.png'),profile:asset('design-reference/09_profile.png'),templates:asset('design-reference/10_templates.png'),tags:asset('design-reference/11_tags.png')};
const screens:Record<string,string>={'/':'home','/fitness':'fitness','/cpa':'cpa','/knowledge':'knowledge','/timeline':'timeline','/capture':'capture','/goals':'goals','/profile':'profile','/templates':'templates','/tags':'tags'};

function BottomNav(){
  const nav=useNavigate(),loc=useLocation();
  const items=[['/',HomeIcon,'首页'],['/timeline',Clock3,'时间'],['/capture',Plus,''],['/knowledge',BookOpen,'知识'],['/profile',UserRound,'我的']] as const;
  return <nav className="bottom-nav" aria-label="主导航">{items.map(([to,Icon,label],index)=><button key={to} className={`${loc.pathname===to?'active':''} ${index===2?'capture-btn':''}`} onClick={()=>nav(to)} aria-label={label||'快速记录'}><span><Icon strokeWidth={index===2?1.6:1.8}/></span>{label&&<small>{label}</small>}</button>)}</nav>;
}

function Shell({children,noNav=false,dark=false,className=''}:{children:ReactNode;noNav?:boolean;dark?:boolean;className?:string}){return <main className={`app-shell ${dark?'dark-page':''} ${className}`}>{children}{!noNav&&<BottomNav/>}</main>}
function PageHeader({title,onBack,actions}:{title:string;onBack?:()=>void;actions?:ReactNode}){return <header className="page-header">{onBack&&<button aria-label="返回" onClick={onBack}><ArrowLeft/></button>}<h1>{title}</h1><span/>{actions}</header>}
function Progress({value}:{value:number}){return <div className="progress"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
function Empty({title,description}:{title:string;description:string}){return <div className="empty-state"><Sparkles/><b>{title}</b><span>{description}</span></div>}
function DomainVisual({line,title,className=''}:{line?:Line;title?:string;className?:string}){const label=title||line?.title||'MYM';return <div className={`domain-visual preset-${line?.preset||'general'} ${className}`}><span>{label.slice(0,1)}</span><i/><i/></div>}

function GoalRow({goal,lines,onClick}:{goal:Goal;lines:Line[];onClick?:()=>void}){const line=lines.find(x=>x.id===goal.domainId);return <button className="goal-row" onClick={onClick}><DomainVisual line={line} title={goal.title}/><div className="goal-info"><b>{goal.title}</b><span>{goal.description||line?.title||'独立目标'}</span><Progress value={goal.progress}/></div><strong>{goal.progress}%</strong></button>}

function Home(){
  const nav=useNavigate();
  const goals=useLiveQuery(()=>db.goals.where('status').equals('focus').sortBy('updatedAt'),[])??[];
  const entries=useLiveQuery(()=>db.entries.orderBy('createdAt').reverse().limit(5).toArray(),[])??[];
  const media=useLiveQuery(()=>db.media.toArray(),[])??[];const lines=useLiveQuery(()=>db.lines.toArray(),[])??[];
  const focus=[...goals].sort((a,b)=>(a.order??999)-(b.order??999)||b.updatedAt.localeCompare(a.updatedAt)).slice(0,5);
  const today=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
  return <Shell className="home-page"><section className="home-hero" data-visual-dynamic onClick={()=>nav('/goals')}><div className="hero-art"><i/><i/><i/></div><div className="hero-copy"><small>{today}</small><h1>更自律<br/>更强壮<br/>更自由</h1><p>把注意力放在真正重要的事情上。</p></div></section>
    <section className="section"><div className="section-title"><h1>当前重点</h1><button onClick={()=>nav('/goals')}>全部 ›</button></div>{focus.length?<div className="goal-card">{focus.map(goal=><GoalRow key={goal.id} goal={goal} lines={lines} onClick={()=>nav(goal.domainId==='fitness'?'/fitness':goal.domainId==='cpa'?'/cpa':'/goals')}/>)}</div>:<Empty title="还没有当前重点" description="把一个目标设为“重点”，它会出现在这里。"/>}</section>
    <section className="section recent"><div className="section-title"><h1>最近人生</h1><button onClick={()=>nav('/timeline')}>全部 ›</button></div>{entries.length?<div className="recent-grid">{entries.slice(0,3).map(entry=>{const p=toEntryPresentation(entry,media,lines),m=selectPrimaryMedia(entry,media);return <button key={entry.id} onClick={()=>nav(`/note/${entry.id}`)}><MediaThumbnail media={m}/><b>{p.displayTitle}</b><span>{p.date} {p.time}</span></button>})}</div>:<Empty title="还没有记录" description="点击下方绿色按钮，写下第一条生活记录。"/>}</section>
  </Shell>;
}

function DomainTabs(){return <div className="domain-tabs">{['总览','记录','数据','知识','资源'].map((label,index)=><button className={index===0?'active':''} key={label}>{label}</button>)}</div>}
function DomainPage({domainId}:{domainId:string}){
  const line=useLiveQuery(()=>db.lines.get(domainId),[domainId]);const goals=useLiveQuery(()=>db.goals.where('domainId').equals(domainId).toArray(),[domainId])??[];
  const entries=useLiveQuery(()=>db.entries.where('domainIds').equals(domainId).reverse().sortBy('createdAt'),[domainId])??[];
  const metrics=useLiveQuery(()=>db.metrics.where('domainId').equals(domainId).reverse().sortBy('recordedAt'),[domainId])??[];
  const media=useLiveQuery(()=>db.media.toArray(),[])??[];const nav=useNavigate();const goal=goals.find(x=>x.status==='focus')||goals.find(x=>x.status==='active');
  if(line===undefined)return <Shell className="domain-page"><div className="page-loading">正在读取本地数据…</div></Shell>;
  if(!line)return <Shell className="domain-page"><Empty title="主线不存在" description="可以在目标页面管理你的主线。"/></Shell>;
  const header=<><section className={`domain-hero preset-${line.preset||'general'}`} data-visual-dynamic><DomainVisual line={line}/><div><small>{line.preset==='fitness'?'BODY & ENERGY':line.preset==='study'?'LEARN & GROW':'LIFE DOMAIN'}</small><h1>{line.title}</h1><p>{line.description}</p></div></section><DomainTabs/></>;
  const recent=<>{entries.length?<div className="domain-entry-list">{entries.slice(0,4).map(entry=>{const p=toEntryPresentation(entry,media,[line]),m=selectPrimaryMedia(entry,media);return <button key={entry.id} onClick={()=>nav(`/note/${entry.id}`)}><MediaThumbnail media={m}/><span><b>{p.displayTitle}</b><small>{p.date} {p.time} · {p.previewText}</small></span><ChevronRight/></button>})}</div>:<Empty title="还没有相关记录" description={`在快速记录中选择“${line.title}”。`}/>}</>;
  if(line.preset==='study'){
    const days=goal?.dueDate?Math.max(0,Math.ceil((new Date(goal.dueDate).getTime()-Date.now())/86400000)):undefined;
    const activeDays=new Set(entries.filter(entry=>Date.now()-new Date(entry.createdAt).getTime()<7*86400000).map(entry=>new Date(entry.createdAt).getDay())).size;
    return <Shell className="domain-page study-page">{header}<div className="page-pad"><article className="count-card"><span>距离考试还有</span><div><b>{days??'—'}</b> 天</div><small>{goal?.dueDate||'未设置考试日期'}</small><label>学习进度 <strong>{goal?.progress??0}%</strong></label><Progress value={goal?.progress??0}/></article><div className="section-title"><h2>科目进度</h2><button>来自真实指标</button></div><div className="subject-grid">{metrics.slice(0,4).map(item=><div key={item.id}>{item.name}<b>{item.value}{item.unit}</b></div>)}{metrics.length===0&&<div>暂无<b>—</b></div>}</div><div className="section-title"><h2>本周状态</h2><button>{activeDays}/7 天</button></div><div className="week">{['一','二','三','四','五','六','日'].map((day,index)=><div key={day}><span className={index<activeDays?'done':''}>{index<activeDays?'✓':'·'}</span><small>{day}</small></div>)}</div><div className="section-title"><h2>最近学习</h2><button onClick={()=>nav(`/capture?domain=${domainId}`)}>新增 ›</button></div>{recent}</div></Shell>;
  }
  if(line.preset==='fitness'){
    const photos=entries.flatMap(entry=>entry.media.map(id=>media.find(item=>item.id===id))).filter((item):item is Media=>Boolean(item&&item.kind==='image')).slice(0,2);
    return <Shell className="domain-page fitness-page">{header}<div className="page-pad"><article className="primary-card"><span>当前目标</span><h1>{goal?.title||'暂未设置目标'}</h1><p>{goal?.dueDate?`目标：${goal.dueDate}`:'在目标管理中创建或关联目标'}{goal&&`　${goal.progress}%`}</p>{goal&&<Progress value={goal.progress}/>}</article><div className="metric-grid">{metrics.slice(0,3).map(item=><article key={item.id}><span>{item.name}</span><b>{item.value} {item.unit}</b><em>{new Date(item.recordedAt).toLocaleDateString('zh-CN')}</em></article>)}{metrics.length===0&&<article className="metric-empty"><span>暂无指标</span><b>—</b><em>模板记录后出现</em></article>}</div><h2>变化对比</h2><div className="compare" data-visual-dynamic><MediaThumbnail media={photos[1]}/><b>→</b><MediaThumbnail media={photos[0]}/></div><div className="section-title"><h2>最近记录</h2><button onClick={()=>nav(`/capture?domain=${domainId}`)}>新增 ›</button></div>{recent}</div></Shell>;
  }
  return <Shell className="domain-page">{header}<div className="page-pad"><article className="primary-card"><span>当前目标</span><h1>{goal?.title||'暂未设置目标'}</h1><p>{goal?.description||'在目标管理中创建或关联目标'}</p>{goal&&<Progress value={goal.progress}/>}</article><div className="section-title"><h2>最近记录</h2><button onClick={()=>nav(`/capture?domain=${domainId}`)}>新增 ›</button></div>{recent}</div></Shell>;
}

function Knowledge(){
  const nodes=useLiveQuery(()=>db.knowledgeNodes.toArray(),[])??[];const links=useLiveQuery(()=>db.knowledgeLinks.toArray(),[])??[];
  const entries=useLiveQuery(()=>db.entries.toArray(),[])??[];const media=useLiveQuery(()=>db.media.toArray(),[])??[];const nav=useNavigate();
  const [scale,setScale]=useState(1),[offset,setOffset]=useState({x:0,y:0}),[category,setCategory]=useState('全部');const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
  const categories=['全部',...Array.from(new Set(nodes.map(x=>x.category).filter(Boolean)))];const visible=category==='全部'?nodes:nodes.filter(x=>x.category===category);const ids=new Set(visible.map(x=>x.id));
  const move=(event:ReactPointerEvent)=>{if(drag.current)setOffset({x:drag.current.ox+event.clientX-drag.current.x,y:drag.current.oy+event.clientY-drag.current.y})};
  return <Shell dark className="knowledge-page"><PageHeader title="知识空间" onBack={()=>nav(-1)} actions={<><button aria-label="搜索知识"><Search/></button><button aria-label="知识菜单"><Ellipsis/></button></>}/><div className="knowledge-tabs">{categories.map(label=><button className={category===label?'active':''} onClick={()=>setCategory(label)} key={label}>{label}</button>)}</div>
    <section className="graph" onWheel={(event:WheelEvent)=>setScale(Math.max(.7,Math.min(1.6,scale-event.deltaY*.001)))} onPointerDown={event=>{drag.current={x:event.clientX,y:event.clientY,ox:offset.x,oy:offset.y};event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={move} onPointerUp={()=>drag.current=null}>
      <div className="graph-controls"><button onClick={()=>setScale(x=>Math.min(1.6,x+.1))}><ZoomIn/></button><button onClick={()=>setScale(x=>Math.max(.7,x-.1))}><ZoomOut/></button></div>
      {visible.length?<div className="graph-plane" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${scale})`}}><svg viewBox="0 0 393 360"><g stroke="#299565" strokeWidth="1.5" opacity=".8">{links.filter(x=>ids.has(x.source)&&ids.has(x.target)).map(link=>{const a=visible.find(x=>x.id===link.source),b=visible.find(x=>x.id===link.target);return a&&b?<line key={link.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}</g></svg>{visible.map((node,index)=>{const linked=entries.find(x=>x.id===node.entryId),record=media.find(x=>x.id===(node.mediaId||linked?.media[0]));return <button key={node.id} className={`graph-node ${index===0?'main':''}`} style={{left:node.x,top:node.y}} onClick={()=>linked&&nav(`/note/${linked.id}`)}><MediaThumbnail media={record}/><i>{node.count}</i><span>{node.title}</span></button>})}</div>:<Empty title="知识空间还是空的" description="知识节点会从你的真实数据和备份中读取。"/>}
    </section><section className="dark-notes"><div className="section-title"><h2>关联笔记 <small>{entries.filter(x=>nodes.some(n=>n.entryId===x.id)).length}</small></h2></div><div className="dark-card">{entries.filter(x=>nodes.some(n=>n.entryId===x.id)).slice(0,4).map(entry=>{const p=toEntryPresentation(entry,media,[]),record=selectPrimaryMedia(entry,media);return <button key={entry.id} onClick={()=>nav(`/note/${entry.id}`)}><MediaThumbnail media={record}/><span><b>{p.displayTitle}</b><small>{p.date} {p.time}</small><em>{p.tags[0]&&`#${p.tags[0]}`}</em></span><ChevronRight/></button>})}</div></section>
  </Shell>;
}

function Timeline(){
  const nav=useNavigate();const entries=useLiveQuery(()=>db.entries.orderBy('createdAt').reverse().toArray(),[])??[];const media=useLiveQuery(()=>db.media.toArray(),[])??[];const lines=useLiveQuery(()=>db.lines.toArray(),[])??[];
  const [filter,setFilter]=useState('全部');const shown=filter==='全部'?entries:entries.filter(x=>x.type===filter||x.emotion&&filter==='情绪');
  return <Shell className="timeline-page"><h1 className="page-title">时间</h1><div className="filter-tabs">{['全部','日记','想法','情绪','待办'].map(label=><button className={filter===label?'active':''} onClick={()=>setFilter(label)} key={label}>{label}</button>)}</div>{shown.length?<div className="timeline-list">{shown.map(entry=>{const p=toEntryPresentation(entry,media,lines),record=selectPrimaryMedia(entry,media);return <article key={entry.id} onClick={()=>nav(`/note/${entry.id}`)}><time>{p.date}</time><i/><MediaThumbnail media={record}/><div><b>{p.displayTitle}</b><p>{p.previewText||'媒体记录'}</p><small>{p.time} · {p.domain?.title||p.tags[0]||entry.type||'记录'}</small></div></article>})}</div>:<Empty title="时间线暂无记录" description="每条真实记录都会按时间出现在这里。"/>}<button className="floating-add" aria-label="新增记录" onClick={()=>nav('/capture')}><Plus/></button></Shell>;
}

function DynamicField({field,value,onChange,onMedia}:{field:TemplateField;value:TemplateFieldValue|undefined;onChange:(value:TemplateFieldValue)=>void;onMedia:()=>void}){
  const common={id:`field-${field.id}`,required:field.required};
  if(field.type==='textarea')return <textarea {...common} placeholder={field.placeholder||`填写${field.label}`} value={String(value??'')} onChange={event=>onChange(event.target.value)}/>;
  if(field.type==='checkbox')return <label className="field-checkbox"><input {...common} type="checkbox" checked={Boolean(value)} onChange={event=>onChange(event.target.checked)}/><span>已完成 / 是</span></label>;
  if(field.type==='select')return <select {...common} value={String(value??'')} onChange={event=>onChange(event.target.value)}><option value="">请选择</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>;
  if(field.type==='rating')return <div className="rating-field">{[1,2,3,4,5].map(number=><button type="button" className={Number(value)>=number?'active':''} key={number} onClick={()=>onChange(number)}>★</button>)}</div>;
  if(field.type==='media')return <button type="button" className="field-media" onClick={onMedia}><ImageIcon/> 添加本地媒体</button>;
  const type=field.type==='number'||field.type==='metric'?'number':field.type==='date'?'date':'text';
  return <div className="field-input"><input {...common} type={type} placeholder={field.placeholder||`填写${field.label}`} value={String(value??'')} onChange={event=>onChange(type==='number'?Number(event.target.value):event.target.value)}/>{field.unit&&<span>{field.unit}</span>}</div>;
}

function QuickCapture(){
  const nav=useNavigate();const [params]=useSearchParams();const editId=params.get('edit')||'';const templateId=params.get('template')||'';const presetDomain=params.get('domain')||'';
  const existing=useLiveQuery(()=>editId?db.entries.get(editId):undefined,[editId]);const templates=useLiveQuery(()=>db.templates.orderBy('order').toArray(),[])??[];const tags=useLiveQuery(()=>db.tags.toArray(),[])??[];
  const lines=useLiveQuery(()=>db.lines.where('archived').equals(0).sortBy('order'),[])??[];const goals=useLiveQuery(()=>db.goals.toArray(),[])??[];const allMedia=useLiveQuery(()=>db.media.toArray(),[])??[];
  const [type,setType]=useState('日记'),[title,setTitle]=useState(''),[content,setContent]=useState(''),[selected,setSelected]=useState<string[]>([]),[mediaIds,setMediaIds]=useState<string[]>([]),[domainId,setDomainId]=useState(presetDomain),[goalId,setGoalId]=useState(''),[chosenTemplate,setChosenTemplate]=useState(templateId),[fieldValues,setFieldValues]=useState<Record<string,TemplateFieldValue>>({}),[tagSearch,setTagSearch]=useState(''),[newTag,setNewTag]=useState(''),[message,setMessage]=useState('');
  const fileRef=useRef<HTMLInputElement>(null),loaded=useRef('');const template=templates.find(x=>x.id===chosenTemplate);
  useEffect(()=>{if(existing&&loaded.current!==existing.id){loaded.current=existing.id;setType(existing.type||'日记');setTitle(existing.title||'');setContent(existing.content);setSelected(existing.tags);setMediaIds(existing.media);setDomainId(existing.domainIds[0]||'');setGoalId(existing.goalIds[0]||'');setChosenTemplate(existing.templateId||'');setFieldValues(existing.fieldValues||{});}},[existing]);
  useEffect(()=>{if(!editId&&template&&loaded.current!==`template:${template.id}`){loaded.current=`template:${template.id}`;setSelected(current=>Array.from(new Set([...current,...template.defaultTags])));}},[template,editId]);
  useEffect(()=>{const viewport=window.visualViewport;const resize=()=>document.documentElement.style.setProperty('--visual-height',`${viewport?.height||window.innerHeight}px`);resize();viewport?.addEventListener('resize',resize);return()=>viewport?.removeEventListener('resize',resize)},[]);
  const pick=async(event:ChangeEvent<HTMLInputElement>)=>{for(const file of Array.from(event.target.files??[])){try{const {record,thumbnailError}=await importMediaFile(file);setMediaIds(current=>[...current,record.id]);if(thumbnailError)setMessage(`${thumbnailError}，视频已保存，可正常播放。`);}catch(error){setMessage(error instanceof Error?error.message:'媒体保存失败');}}event.target.value='';};
  const openPicker=(accept='*/*')=>{if(fileRef.current){fileRef.current.accept=accept;fileRef.current.click();}};
  const chooseTemplate=(id:string)=>{setChosenTemplate(id);const next=templates.find(x=>x.id===id);if(next)setSelected(current=>Array.from(new Set([...current,...next.defaultTags])));};
  const addTag=async(value:string)=>{const name=normalizeTag(value);if(!name)return;await ensureTags([name]);setSelected(current=>Array.from(new Set([...current,name])));setNewTag('');setTagSearch('');};
  const hash=content.match(/#([^\s#]*)$/)?.[1]??'';const suggestions=(hash?tags.filter(tag=>tag.name.startsWith(hash)):tags.filter(tag=>tag.name.includes(tagSearch.replace(/^#/,'')))).sort((a,b)=>b.count-a.count).slice(0,8);
  const save=async()=>{try{
    if(!title.trim()&&!content.trim()&&!mediaIds.length&&!Object.values(fieldValues).some(Boolean)){setMessage('请先写一点内容或添加媒体');return;}
    const now=new Date().toISOString(),id=existing?.id||crypto.randomUUID();const cleanTags=await ensureTags(selected);const snapshot=template?{title:template.title,description:template.description,fields:structuredClone(template.fields),sections:[...template.sections],defaultTags:[...template.defaultTags]}:existing?.templateSnapshot;
    const mediaFieldIds=template?.fields.filter(x=>x.type==='media').map(x=>x.id)??[];const values={...fieldValues};for(const fieldId of mediaFieldIds)values[fieldId]=mediaIds;
    const entry:Entry={id,title:title.trim()||undefined,content,type,createdAt:existing?.createdAt||now,updatedAt:now,domainIds:domainId?[domainId]:[],goalIds:goalId?[goalId]:[],tags:cleanTags,templateId:template?.id||existing?.templateId,templateSnapshot:snapshot,fieldValues:values,emotion:type==='情绪'?'记录':undefined,media:mediaIds,metrics:[]};
    await db.transaction('rw',[db.entries,db.metrics],async()=>{const oldMetrics=existing?.metrics??[];await db.metrics.bulkDelete(oldMetrics);const records=(template?.fields??snapshot?.fields??[]).filter(x=>x.type==='metric'&&Number.isFinite(Number(values[x.id]))).map(field=>({id:crypto.randomUUID(),entryId:id,domainId:domainId||undefined,name:field.label,value:Number(values[field.id]),unit:field.unit||'',recordedAt:now}));entry.metrics=records.map(x=>x.id);await db.entries.put(entry);if(records.length)await db.metrics.bulkAdd(records);});
    await recalculateTagCounts();nav(`/note/${id}`);
  }catch(error){setMessage(error instanceof Error?error.message:'保存失败');}};
  return <Shell noNav className="capture-page"><PageHeader title={editId?'编辑记录':'快速记录'} onBack={()=>nav(-1)} actions={<button className="text-action" onClick={save}>完成</button>}/><div className="capture-body">
    <div className="capture-types">{['日记','灵感','想法','情绪','待办'].map(label=><button className={label===type?'active':''} onClick={()=>setType(label)} key={label}>{label}</button>)}</div>
    <article className="template-choice"><small>使用模板（可选）</small><select aria-label="选择模板" value={chosenTemplate} onChange={event=>chooseTemplate(event.target.value)}><option value="">空白记录</option>{templates.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></article>
    <input className="capture-title" aria-label="记录标题" placeholder="标题（可选）" value={title} onChange={event=>setTitle(event.target.value)}/>
    {template&&<div className="template-fields">{[...template.fields].sort((a,b)=>(a.order??0)-(b.order??0)).map(field=><label key={field.id}><span>{field.label}{field.required&&<em>*</em>}</span><DynamicField field={field} value={fieldValues[field.id]} onChange={value=>setFieldValues(current=>({...current,[field.id]:value}))} onMedia={()=>openPicker('image/*,video/*,audio/*')}/></label>)}</div>}
    <textarea className="capture-content" aria-label="记录内容" placeholder={template?'补充内容……':'此刻的想法……'} value={content} onChange={event=>setContent(event.target.value)}/>{hash&&suggestions.length>0&&<div className="tag-suggestions">{suggestions.map(tag=><button key={tag.id} onClick={()=>{addTag(tag.name);setContent(value=>value.replace(/#[^\s#]*$/,'#'+tag.name+' '))}}>#{tag.name}</button>)}</div>}
    {mediaIds.length>0&&<div className="media-previews">{mediaIds.map(id=>{const record=allMedia.find(x=>x.id===id);return <div key={id}><MediaThumbnail media={record}/><button aria-label="移除媒体" onClick={()=>setMediaIds(current=>current.filter(x=>x!==id))}><X/></button></div>})}</div>}
    <input hidden multiple ref={fileRef} type="file" onChange={pick}/><div className="media-actions">{[[ImageIcon,'图片','image/*'],[Video,'视频','video/*'],[Mic,'音频','audio/*'],[Paperclip,'附件','*/*']].map(([Icon,label,accept])=><button key={label as string} onClick={()=>openPicker(accept as string)}>{typeof Icon!=='string'&&<Icon/>}<span>{label as string}</span></button>)}</div>
    <div className="capture-links"><label>主线<select value={domainId} onChange={event=>setDomainId(event.target.value)}><option value="">不选择</option>{lines.map(line=><option key={line.id} value={line.id}>{line.title}</option>)}</select></label><label>目标<select value={goalId} onChange={event=>setGoalId(event.target.value)}><option value="">不选择</option>{goals.filter(goal=>!domainId||goal.domainId===domainId).map(goal=><option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label></div>
    <div className="section-title"><h2>标签</h2><button onClick={()=>nav('/tags')}>管理 ›</button></div><article className="tag-picker"><small>已选择</small><div>{selected.map(name=><button className="selected" key={name} onClick={()=>setSelected(current=>current.filter(x=>x!==name))}>#{name} ×</button>)}</div><label className="tag-search"><Search/><input placeholder="搜索标签" value={tagSearch} onChange={event=>setTagSearch(event.target.value)}/></label><div>{suggestions.map(tag=><button key={tag.id} className={selected.includes(tag.name)?'selected':''} onClick={()=>setSelected(current=>current.includes(tag.name)?current.filter(x=>x!==tag.name):[...current,tag.name])}>#{tag.name}</button>)}</div><div className="inline-create"><input placeholder="新标签" value={newTag} onChange={event=>setNewTag(event.target.value)}/><button onClick={()=>addTag(newTag)}>创建</button></div></article>
  </div>{message&&<Toast message={message}/>}</Shell>;
}

function Goals(){
  const goals=useLiveQuery(()=>db.goals.toArray(),[])??[];const lines=useLiveQuery(()=>db.lines.orderBy('order').toArray(),[])??[];const [tab,setTab]=useState('active'),[goalOpen,setGoalOpen]=useState(false),[linesOpen,setLinesOpen]=useState(false);const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[domainId,setDomainId]=useState(''),[status,setStatus]=useState<Goal['status']>('active'),[dueDate,setDueDate]=useState(''),[message,setMessage]=useState('');
  const shown=goals.filter(goal=>tab==='done'?goal.status==='done':tab==='paused'?goal.status==='paused':goal.status!=='done'&&goal.status!=='paused').sort((a,b)=>(a.order??999)-(b.order??999)||b.updatedAt.localeCompare(a.updatedAt));
  const addGoal=async()=>{if(!title.trim()){setMessage('请输入目标名称');return;}const now=new Date().toISOString();await db.goals.add({id:crypto.randomUUID(),title:title.trim(),description:description.trim(),status,progress:0,order:goals.length,dueDate:dueDate||undefined,domainId:domainId||undefined,createdAt:now,updatedAt:now});setGoalOpen(false);setTitle('');setDescription('');};
  return <Shell className="goals-page"><div className="title-with-action"><h1 className="page-title">我的目标</h1><button onClick={()=>setLinesOpen(true)}>管理主线</button></div><div className="goal-tabs">{[['active','进行中'],['done','已完成'],['paused','已暂停']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>{shown.length?<div className="goal-card goals-list">{shown.map(goal=><GoalRow key={goal.id} goal={goal} lines={lines}/>)}</div>:<Empty title="这里还没有目标" description="新建任意目标，无需修改代码。"/>}<button className="floating-add" aria-label="新建目标" onClick={()=>setGoalOpen(true)}><Plus/></button>
    {goalOpen&&<Dialog title="新建目标" onClose={()=>setGoalOpen(false)} actions={<><button onClick={()=>setGoalOpen(false)}>取消</button><button className="primary" onClick={addGoal}>保存目标</button></>}><div className="form-stack"><label>目标名称<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>说明<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>所属主线<select value={domainId} onChange={e=>setDomainId(e.target.value)}><option value="">独立目标</option>{lines.filter(x=>!x.archived).map(line=><option key={line.id} value={line.id}>{line.title}</option>)}</select></label><label>状态<select value={status} onChange={e=>setStatus(e.target.value as Goal['status'])}><option value="focus">当前重点</option><option value="active">进行中</option><option value="paused">暂停</option></select></label><label>截止日期<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div></Dialog>}
    {linesOpen&&<LineManager lines={lines} onClose={()=>setLinesOpen(false)} onMessage={setMessage}/>} {message&&<Toast message={message}/>}</Shell>;
}

function LineManager({lines,onClose,onMessage}:{lines:Line[];onClose:()=>void;onMessage:(value:string)=>void}){
  const [title,setTitle]=useState(''),[editing,setEditing]=useState<Line|undefined>(),[name,setName]=useState('');
  const add=async()=>{if(!title.trim())return;await db.lines.add({id:crypto.randomUUID(),title:title.trim(),description:'',order:lines.length,archived:false,preset:'general'});setTitle('');};
  const move=async(line:Line,delta:number)=>{const ordered=[...lines].sort((a,b)=>a.order-b.order),index=ordered.findIndex(x=>x.id===line.id),other=ordered[index+delta];if(!other)return;await db.transaction('rw',db.lines,async()=>{await db.lines.update(line.id,{order:other.order});await db.lines.update(other.id,{order:line.order});});};
  const remove=async(line:Line)=>{if(await db.goals.where('domainId').equals(line.id).count()||await db.entries.where('domainIds').equals(line.id).count()){onMessage('该主线仍有关联目标或记录，请先归档');return;}await db.lines.delete(line.id);};
  return <Dialog title="管理主线" onClose={onClose}><div className="inline-create"><input placeholder="新主线名称" value={title} onChange={e=>setTitle(e.target.value)}/><button onClick={add}>新建</button></div><div className="manage-lines">{lines.map(line=><div key={line.id}><span><b>{line.title}</b><small>{line.archived?'已归档':line.preset==='fitness'?'健身展示':line.preset==='study'?'学习展示':'通用展示'}</small></span><button onClick={()=>move(line,-1)}><ArrowUp/></button><button onClick={()=>move(line,1)}><ArrowDown/></button><button onClick={()=>db.lines.update(line.id,{archived:!line.archived})}>{line.archived?'恢复':'归档'}</button><button onClick={()=>{setEditing(line);setName(line.title)}}>重命名</button><button onClick={()=>remove(line)}><Trash2/></button></div>)}</div>{editing&&<Dialog title="重命名主线" onClose={()=>setEditing(undefined)} actions={<button className="primary" onClick={async()=>{if(name.trim())await db.lines.update(editing.id,{title:name.trim()});setEditing(undefined)}}>保存</button>}><div className="form-stack"><label>名称<input value={name} onChange={e=>setName(e.target.value)}/></label></div></Dialog>}</Dialog>;
}

function NoteDetail(){
  const {id=''}=useParams();const nav=useNavigate();const entry=useLiveQuery(()=>db.entries.get(id),[id]);const media=useLiveQuery(()=>entry?db.media.bulkGet(entry.media):[],[entry?.updatedAt])??[];const lines=useLiveQuery(()=>db.lines.toArray(),[])??[];const metrics=useLiveQuery(()=>entry?db.metrics.bulkGet(entry.metrics):[],[entry?.updatedAt])??[];const [deleteOpen,setDeleteOpen]=useState(false),[deleteMedia,setDeleteMedia]=useState(true),[message,setMessage]=useState('');
  if(entry===undefined)return <Shell noNav className="note-page"><PageHeader title="笔记详情" onBack={()=>nav(-1)}/><div className="page-loading">正在读取本地数据…</div></Shell>;
  if(!entry)return <Shell noNav className="note-page"><PageHeader title="笔记详情" onBack={()=>nav(-1)}/><Empty title="记录不存在" description="它可能已被删除，其他本地数据不受影响。"/></Shell>;
  const p=toEntryPresentation(entry,media.filter(Boolean) as Media[],lines),domain=lines.find(x=>entry.domainIds.includes(x.id));
  const remove=async()=>{const ids=[...entry.media];await db.entries.delete(entry.id);if(deleteMedia)for(const mediaId of ids)await deleteMediaRecordIfUnreferenced(mediaId,entry.id);await recalculateTagCounts();nav('/timeline');};
  return <Shell noNav className="note-page"><PageHeader title="笔记详情" onBack={()=>nav(-1)} actions={<><button aria-label="编辑" onClick={()=>nav(`/capture?edit=${entry.id}`)}>编辑</button><button aria-label="删除" onClick={()=>setDeleteOpen(true)}><Trash2/></button></>}/>{media.filter(Boolean).length>0&&<div className="note-media-strip">{media.filter(Boolean).map(item=><FullMedia key={item!.id} media={item!}/>)}</div>}<div className="note-body"><h1>{p.displayTitle}</h1><p className="muted">{new Date(entry.createdAt).toLocaleString('zh-CN',{dateStyle:'medium',timeStyle:'short'})}{domain&&` · ${domain.title}`}</p><div className="chips">{entry.tags.map(tag=><span key={tag}>#{tag}</span>)}</div>{entry.templateSnapshot&&<article className="used-template"><span><small>记录模板快照</small><b>{entry.templateSnapshot.title}</b></span></article>}
    {entry.templateSnapshot?.fields.map(field=>{const value=entry.fieldValues?.[field.id];if(value==null||value===''||value===false)return null;return <article className="field-value" key={field.id}><h3>{field.label}</h3><p>{Array.isArray(value)?value.join('、'):field.type==='rating'?`${value} / 5`:String(value)} {field.unit||''}</p></article>})}<div className="section-title"><h2>笔记内容</h2><button onClick={()=>nav(`/capture?edit=${entry.id}`)}>编辑</button></div><article className="note-content"><p>{entry.content||'这是一条媒体记录。'}</p></article>{metrics.filter(Boolean).length>0&&<div className="note-metrics">{metrics.filter(Boolean).map(metric=><span key={metric!.id}><b>{metric!.value} {metric!.unit}</b><small>{metric!.name}</small></span>)}</div>}</div>
    {deleteOpen&&<Dialog title="删除这条记录？" onClose={()=>setDeleteOpen(false)} actions={<><button onClick={()=>setDeleteOpen(false)}>取消</button><button className="danger" onClick={remove}>确认删除</button></>}><p>删除后无法撤销。你的其他记录不会受影响。</p><label className="field-checkbox"><input type="checkbox" checked={deleteMedia} onChange={e=>setDeleteMedia(e.target.checked)}/><span>同时删除这条记录独占的媒体</span></label></Dialog>}{message&&<Toast message={message}/>}</Shell>;
}

function Profile(){
  const nav=useNavigate();const counts=useLiveQuery(async()=>({entries:await db.entries.count(),goals:await db.goals.where('status').anyOf('focus','active').count(),tags:await db.tags.count()}),[])??{entries:0,goals:0,tags:0};
  const [storage,setStorage]=useState<StorageStatus>({persisted:false,usage:0,quota:0}),[backupOpen,setBackupOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{requestPersistentStorage().then(setStorage).catch(()=>undefined)},[]);const ratio=storage.quota?storage.usage/storage.quota:0;
  return <Shell className="profile-page"><section className="profile-hero"><div className="avatar"><UserRound/></div><h1>更好的自己</h1><p>持续成长 · 保持清醒</p></section><div className="stats"><b>{counts.entries}<small>记录</small></b><b>{counts.goals}<small>进行中目标</small></b><b>{counts.tags}<small>标签</small></b></div><div className="storage-card"><div><HardDrive/><span><b>本地存储</b><small>持久化：{storage.persisted?'已开启':'未开启'}</small></span></div><p>已使用 {formatBytes(storage.usage)} · 配额 {formatBytes(storage.quota)}</p><Progress value={ratio*100}/>{ratio>.8&&<em>本地存储空间即将不足，请备份或清理媒体。</em>}</div><div className="profile-actions">
    <button onClick={()=>setSearchOpen(true)}><Search/><span><b>全局搜索</b><small>记录、标签、目标、主线和模板</small></span><ChevronRight/></button><button onClick={()=>nav('/goals')}><BarChart3/><span><b>目标与主线</b><small>管理长期方向和当前重点</small></span><ChevronRight/></button><button onClick={()=>nav('/tags')}><TagIcon/><span><b>标签管理</b><small>整理、合并和复用标签</small></span><ChevronRight/></button><button onClick={()=>nav('/templates')}><Notebook/><span><b>模板管理</b><small>新建、编辑、复制记录模板</small></span><ChevronRight/></button><button onClick={()=>setBackupOpen(true)}><Share2/><span><b>备份与恢复</b><small>完整 ZIP，包括全部媒体</small></span><ChevronRight/></button><button onClick={()=>setSettingsOpen(true)}><Settings/><span><b>本地维护</b><small>清理孤儿媒体与示例数据</small></span><ChevronRight/></button>
  </div>{backupOpen&&<BackupDialog onClose={()=>setBackupOpen(false)} onMessage={setMessage}/>} {searchOpen&&<SearchDialog onClose={()=>setSearchOpen(false)}/>} {settingsOpen&&<MaintenanceDialog onClose={()=>setSettingsOpen(false)} onMessage={setMessage}/>} {message&&<Toast message={message}/>}</Shell>;
}

function BackupDialog({onClose,onMessage}:{onClose:()=>void;onMessage:(message:string)=>void}){
  const [busy,setBusy]=useState(''),[progress,setProgress]=useState(''),[file,setFile]=useState<File>(),[summary,setSummary]=useState<BackupSummary>(),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
  const exportAll=async()=>{try{setBusy('正在创建完整备份');const {blob}=await createBackupZip((current,total)=>setProgress(`${current}/${total}`));downloadBlob(blob,`MYM-Backup-${new Date().toISOString().slice(0,10)}.zip`);onMessage('完整备份已生成');}catch(e){setError(e instanceof Error?e.message:'备份失败');}finally{setBusy('');}};
  const select=async(event:ChangeEvent<HTMLInputElement>)=>{const selected=event.target.files?.[0];if(!selected)return;try{setError('');setBusy('正在验证备份');setFile(selected);setSummary(await inspectBackupZip(selected));}catch(e){setFile(undefined);setSummary(undefined);setError(e instanceof Error?e.message:'备份无效');}finally{setBusy('');}};
  const restore=async()=>{if(!file)return;try{setBusy('正在恢复');await restoreBackupZip(file,(current,total)=>setProgress(`${current}/${total}`));onMessage('备份已完整恢复');onClose();}catch(e){setError(e instanceof Error?e.message:'恢复失败');}finally{setBusy('');}};
  return <Dialog title="备份与恢复" onClose={onClose}><div className="backup-options"><button onClick={exportAll}><Database/><span><b>导出完整 ZIP</b><small>数据库 + 图片 + 视频 + 音频 + 缩略图</small></span></button><button onClick={()=>input.current?.click()}><RefreshCw/><span><b>选择备份恢复</b><small>先验证，确认后才替换数据</small></span></button><input hidden ref={input} type="file" accept=".zip,application/zip" onChange={select}/></div>{busy&&<p className="busy-line">{busy} {progress}</p>}{error&&<p className="error-line">{error}</p>}{summary&&<div className="restore-summary"><h3>发现：</h3><p>{summary.entries} 条记录<br/>{summary.goals} 个目标<br/>{summary.tags} 个标签<br/>{summary.images} 张图片<br/>{summary.videos} 个视频<br/>{summary.audio} 段音频<br/>{summary.knowledge} 个知识节点</p><button className="primary" onClick={restore} disabled={Boolean(busy)}>确认恢复</button></div>}</Dialog>;
}

function SearchDialog({onClose}:{onClose:()=>void}){
  const nav=useNavigate();const [query,setQuery]=useState('');const entries=useLiveQuery(()=>db.entries.toArray(),[])??[];const goals=useLiveQuery(()=>db.goals.toArray(),[])??[];const lines=useLiveQuery(()=>db.lines.toArray(),[])??[];const templates=useLiveQuery(()=>db.templates.toArray(),[])??[];const media=useLiveQuery(()=>db.media.toArray(),[])??[];
  const q=query.trim().toLowerCase();const entryResults=q?entries.filter(x=>[x.title,x.content,...x.tags].some(value=>value?.toLowerCase().includes(q))):[];const other=q?[...goals.map(x=>({kind:'目标',title:x.title})),...lines.map(x=>({kind:'主线',title:x.title})),...templates.map(x=>({kind:'模板',title:x.title}))].filter(x=>x.title.toLowerCase().includes(q)):[];
  return <Dialog title="全局搜索" onClose={onClose}><label className="searchbox"><Search/><input autoFocus placeholder="搜索本地内容" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="search-results">{entryResults.map(entry=>{const p=toEntryPresentation(entry,media,lines);return <button key={entry.id} onClick={()=>{onClose();nav(`/note/${entry.id}`)}}><b>{p.displayTitle}</b><small>{p.previewText}</small></button>})}{other.map((item,index)=><div key={`${item.kind}-${index}`}><b>{item.title}</b><small>{item.kind}</small></div>)}{q&&!entryResults.length&&!other.length&&<Empty title="没有找到" description="搜索仅在这台 iPhone 本地进行。"/>}</div></Dialog>;
}

function MaintenanceDialog({onClose,onMessage}:{onClose:()=>void;onMessage:(message:string)=>void}){
  const [busy,setBusy]=useState(false),[confirmSeed,setConfirmSeed]=useState(false);
  const scan=async()=>{setBusy(true);const result=await findOrphanMedia();if(!result.databaseOrphans.length&&!result.filesystemOrphans.length){onMessage('没有发现未使用媒体');setBusy(false);return;}const count=await cleanOrphanMedia(result);onMessage(`已清理 ${count} 个未使用媒体文件`);setBusy(false);};
  return <Dialog title="本地维护" onClose={onClose}><div className="maintenance-actions"><button onClick={scan} disabled={busy}><Trash2/><span><b>清理未使用媒体</b><small>只清理没有记录或知识节点引用的文件</small></span></button><button onClick={()=>setConfirmSeed(true)}><CircleDot/><span><b>清除示例数据</b><small>删除示例主线与目标，不删除你的记录</small></span></button></div>{confirmSeed&&<div className="inline-confirm"><p>确认删除健身、CPA、英语示例主线及示例目标？</p><button onClick={()=>setConfirmSeed(false)}>取消</button><button className="danger" onClick={async()=>{await clearExampleData();setConfirmSeed(false);onMessage('示例数据已清除')}}>确认清除</button></div>}</Dialog>;
}

const iconMap:Record<string,typeof FileText>={FileText,Notebook,BookOpen,Play,Users,Briefcase:BriefcaseBusiness,CircleDot,RefreshCw};
const fieldTypeLabels:Record<TemplateFieldType,string>={text:'单行文字',textarea:'多行文字',number:'数字',date:'日期',checkbox:'勾选',select:'选择',rating:'评分',media:'媒体',metric:'指标'};
function Templates(){
  const nav=useNavigate();const templates=useLiveQuery(()=>db.templates.orderBy('order').toArray(),[])??[];const [query,setQuery]=useState(''),[editing,setEditing]=useState<Template>();
  const create=()=>setEditing({id:crypto.randomUUID(),title:'',description:'',icon:'FileText',fields:[],sections:['补充内容'],defaultTags:[],order:templates.length});
  const move=async(template:Template,delta:number)=>{const index=templates.findIndex(x=>x.id===template.id),other=templates[index+delta];if(!other)return;await db.transaction('rw',db.templates,async()=>{await db.templates.update(template.id,{order:other.order});await db.templates.update(other.id,{order:template.order});});};
  return <Shell noNav className="manage-page templates-page"><PageHeader title="模板管理" onBack={()=>nav(-1)} actions={<button onClick={create}><Plus/></button>}/><div className="manage-pad"><label className="searchbox"><Search/><input placeholder="搜索模板" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="template-grid">{templates.filter(x=>`${x.title}${x.description}`.includes(query)).map(template=><TemplateCard key={template.id} template={template} onUse={()=>nav(`/capture?template=${template.id}`)} onEdit={()=>setEditing(structuredClone(template))} onCopy={()=>db.templates.add({...structuredClone(template),id:crypto.randomUUID(),title:`${template.title} 副本`,order:templates.length})} onMove={delta=>move(template,delta)}/>)}</div><button className="new-template" onClick={create}><Plus/> 新建自定义模板</button></div>{editing&&<TemplateEditor value={editing} onClose={()=>setEditing(undefined)} onSave={async value=>{await ensureTags(value.defaultTags);await db.templates.put(value);setEditing(undefined)}} onDelete={templates.some(x=>x.id===editing.id)?async()=>{await db.templates.delete(editing.id);setEditing(undefined)}:undefined}/>}</Shell>;
}
function TemplateCard({template,onUse,onEdit,onCopy,onMove}:{template:Template;onUse:()=>void;onEdit:()=>void;onCopy:()=>void;onMove:(delta:number)=>void}){const Icon=iconMap[template.icon]??FileText;return <article><div className="template-icon"><Icon/></div><h2>{template.title}</h2><p>{template.description}</p><footer><button onClick={onUse}>使用</button><span><button onClick={onEdit}>编辑</button> · <button onClick={onCopy}>复制</button></span></footer><div className="card-order"><button onClick={()=>onMove(-1)}><ArrowUp/></button><button onClick={()=>onMove(1)}><ArrowDown/></button></div></article>}
function TemplateEditor({value,onClose,onSave,onDelete}:{value:Template;onClose:()=>void;onSave:(value:Template)=>void;onDelete?:()=>void}){
  const [draft,setDraft]=useState(value),[tagText,setTagText]=useState(value.defaultTags.join('，'));
  const updateField=(id:string,patch:Partial<TemplateField>)=>setDraft(current=>({...current,fields:current.fields.map(field=>field.id===id?{...field,...patch}:field)}));
  const addField=()=>setDraft(current=>({...current,fields:[...current.fields,{id:crypto.randomUUID(),label:'新字段',type:'text',order:current.fields.length}]}));
  const moveField=(index:number,delta:number)=>setDraft(current=>{const fields=[...current.fields],target=index+delta;if(target<0||target>=fields.length)return current;[fields[index],fields[target]]=[fields[target],fields[index]];return {...current,fields:fields.map((field,order)=>({...field,order}))}});
  return <Dialog title="编辑模板" onClose={onClose} actions={<>{onDelete&&<button className="danger" onClick={onDelete}>删除</button>}<button className="primary" onClick={()=>onSave({...draft,title:draft.title.trim()||'未命名模板',defaultTags:tagText.split(/[，,]/).map(normalizeTag).filter(Boolean)})}>保存模板</button></>}><div className="form-stack"><label>模板名称<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>描述<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>默认标签<input value={tagText} onChange={e=>setTagText(e.target.value)} placeholder="用逗号分隔"/></label></div><div className="field-editor"><div className="section-title"><h3>字段</h3><button onClick={addField}><Plus/> 添加</button></div>{draft.fields.map((field,index)=><article key={field.id}><input aria-label="字段名称" value={field.label} onChange={e=>updateField(field.id,{label:e.target.value})}/><select value={field.type} onChange={e=>updateField(field.id,{type:e.target.value as TemplateFieldType})}>{Object.entries(fieldTypeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><label><input type="checkbox" checked={field.required||false} onChange={e=>updateField(field.id,{required:e.target.checked})}/> 必填</label>{field.type==='select'&&<input placeholder="选项，用逗号分隔" value={field.options?.join(',')||''} onChange={e=>updateField(field.id,{options:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/>} {(field.type==='number'||field.type==='metric')&&<input placeholder="单位" value={field.unit||''} onChange={e=>updateField(field.id,{unit:e.target.value})}/>}<div><button onClick={()=>moveField(index,-1)}><ArrowUp/></button><button onClick={()=>moveField(index,1)}><ArrowDown/></button><button onClick={()=>setDraft(current=>({...current,fields:current.fields.filter(x=>x.id!==field.id)}))}><Trash2/></button></div></article>)}</div><label className="field-checkbox"><input type="checkbox" checked={draft.sections.includes('补充内容')} onChange={e=>setDraft({...draft,sections:e.target.checked?['补充内容']:[]})}/><span>保留自由补充内容区</span></label></Dialog>;
}

function Tags(){
  const nav=useNavigate();const tags=useLiveQuery(()=>db.tags.toArray(),[])??[];const [query,setQuery]=useState(''),[createOpen,setCreateOpen]=useState(false),[newName,setNewName]=useState(''),[active,setActive]=useState<Tag>(),[mode,setMode]=useState<'menu'|'rename'|'merge'|'delete'>('menu'),[value,setValue]=useState('');
  const close=()=>{setActive(undefined);setMode('menu');setValue('')};const sorted=[...tags].sort((a,b)=>b.count-a.count||b.lastUsedAt.localeCompare(a.lastUsedAt));
  return <Shell noNav className="manage-page tags-page"><PageHeader title="标签管理" onBack={()=>nav(-1)} actions={<button onClick={()=>setCreateOpen(true)}><Plus/></button>}/><div className="manage-pad"><label className="searchbox"><Search/><input placeholder="搜索标签" value={query} onChange={e=>setQuery(e.target.value)}/></label><article className="tag-rule"><small>标签规则</small><p>用过的标签会自动保留；计数和最近使用时间由真实记录重新计算。删除标签不会删除笔记。</p></article><div className="section-title"><h2>全部标签</h2><button onClick={()=>recalculateTagCounts()}>重新统计</button></div><div className="tag-list">{sorted.filter(tag=>tag.name.includes(query.replace(/^#/,''))).map(tag=><div key={tag.id}><b>#{tag.name}</b><span>{tag.count} 条记录</span><button onClick={()=>{setActive(tag);setMode('menu')}}><MoreHorizontal/></button></div>)}</div></div>
    {createOpen&&<Dialog title="创建标签" onClose={()=>setCreateOpen(false)} actions={<button className="primary" onClick={async()=>{await ensureTags([newName]);setCreateOpen(false);setNewName('')}}>创建</button>}><div className="form-stack"><label>标签名称<input autoFocus value={newName} onChange={e=>setNewName(e.target.value)}/></label></div></Dialog>}
    {active&&<Dialog title={`#${active.name}`} onClose={close}>{mode==='menu'?<div className="action-sheet"><button onClick={()=>{setMode('rename');setValue(active.name)}}>重命名</button><button onClick={()=>setMode('merge')}>合并到其他标签</button><button className="danger" onClick={()=>setMode('delete')}>删除</button></div>:mode==='delete'?<div className="confirm-block"><p>只会从记录和模板移除此标签，不会删除任何笔记。</p><button onClick={close}>取消</button><button className="danger" onClick={async()=>{await deleteTag(active.id);close()}}>确认删除</button></div>:<div className="form-stack"><label>{mode==='rename'?'新名称':'合并到'}{mode==='merge'?<select value={value} onChange={e=>setValue(e.target.value)}><option value="">请选择标签</option>{tags.filter(x=>x.id!==active.id).map(tag=><option key={tag.id} value={tag.id}>#{tag.name}</option>)}</select>:<input value={value} onChange={e=>setValue(e.target.value)}/>}</label><button className="primary" onClick={async()=>{if(mode==='rename')await renameTag(active.id,value);else if(value)await mergeTags([active.id],value);close()}}>保存</button></div>}</Dialog>}
  </Shell>;
}

function Overlay(){const location=useLocation();const [opacity,setOpacity]=useState(.5);const enabled=new URLSearchParams(location.search).get('debugOverlay')==='1';if(!enabled)return null;const key=location.pathname.startsWith('/note')?'note':screens[location.pathname]??'home';return <><img className="debug-overlay" style={{opacity}} src={refs[key]} alt="视觉对齐参考"/><div className="overlay-control"><label>Overlay {Math.round(opacity*100)}%</label><input type="range" min="0" max="1" step=".25" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></div></>}

export default function App(){
  const location=useLocation();const fixture=new URLSearchParams(location.search).get('fixture')==='1';
  useEffect(()=>{(async()=>{if(fixture)await ensureVisualFixtures();else await ensureSeedData();await recalculateTagCounts()})();requestPersistentStorage().catch(()=>undefined)},[fixture]);
  return <><Routes><Route path="/" element={<Home/>}/><Route path="/fitness" element={<DomainPage domainId="fitness"/>}/><Route path="/cpa" element={<DomainPage domainId="cpa"/>}/><Route path="/knowledge" element={<Knowledge/>}/><Route path="/timeline" element={<Timeline/>}/><Route path="/capture" element={<QuickCapture/>}/><Route path="/goals" element={<Goals/>}/><Route path="/note/:id" element={<NoteDetail/>}/><Route path="/profile" element={<Profile/>}/><Route path="/templates" element={<Templates/>}/><Route path="/tags" element={<Tags/>}/><Route path="*" element={<Shell><Empty title="页面不存在" description="返回首页继续使用 MYM。"/></Shell>}/></Routes><Overlay/></>;
}
