import { useEffect, useMemo, useRef, useState, type ChangeEvent, type PointerEvent as ReactPointerEvent, type ReactNode, type WheelEvent } from 'react';
import { Routes, Route, useLocation, useNavigate } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import {
  ArrowLeft, BarChart3, BookOpen, BriefcaseBusiness, Check, ChevronRight, CircleDot, Clock3, Ellipsis,
  File, FileText, Home as HomeIcon, Image as ImageIcon, Lightbulb, Link2, ListTodo, Mic, MoreHorizontal,
  Notebook, Paperclip, Play, Plus, RefreshCw, Search, Settings, Share2, Tag as TagIcon, Trash2, UserRound,
  Users, Video, X, ZoomIn, ZoomOut
} from 'lucide-react';
import { db, ensureSeedData } from './data/db';
import { saveMedia, saveThumbnail, videoThumbnail } from './data/opfs';
import type { Goal, Media as MediaRecord, Template } from './types';

const asset=(path:string)=>`${import.meta.env.BASE_URL}${path.replace(/^\//,'')}`;
const refs:Record<string,string>={
  home:asset('design-reference/01_home.png'),fitness:asset('design-reference/02_fitness.png'),cpa:asset('design-reference/03_cpa.png'),knowledge:asset('design-reference/04_knowledge.png'),timeline:asset('design-reference/05_timeline.png'),capture:asset('design-reference/06_quick_capture.png'),goals:asset('design-reference/07_goals.png'),note:asset('design-reference/08_note_detail.png'),profile:asset('design-reference/09_profile.png'),templates:asset('design-reference/10_templates.png'),tags:asset('design-reference/11_tags.png')
};
const screens:Record<string,string>={'/':'home','/fitness':'fitness','/cpa':'cpa','/knowledge':'knowledge','/timeline':'timeline','/capture':'capture','/goals':'goals','/profile':'profile','/templates':'templates','/tags':'tags'};

function RefSlice({screen,top=0,height,className=''}:{screen:string;top?:number;height:number;className?:string}){
  return <div className={`ref-slice ${className}`} style={{height}}><img src={refs[screen]} style={{top:-top}} alt="" /></div>;
}

function StatusBar({dark=false}:{dark?:boolean}) { return <div className={`statusbar ${dark?'dark':''}`}><b>9:41</b><span>▮▮▮ ◉ ▰</span></div>; }

function BottomNav(){
  const nav=useNavigate(), loc=useLocation();
  const items=[['/',HomeIcon,'首页'],['/timeline',Clock3,'时间'],['/capture',Plus,''],['/knowledge',BookOpen,'知识'],['/profile',UserRound,'我的']] as const;
  return <nav className="bottom-nav" aria-label="主导航">{items.map(([to,Icon,label],i)=><button key={to} className={`${loc.pathname===to?'active':''} ${i===2?'capture-btn':''}`} onClick={()=>nav(to)} aria-label={label||'快速记录'}><span><Icon strokeWidth={i===2?1.6:1.8}/></span>{label&&<small>{label}</small>}</button>)}</nav>;
}

function Shell({children,noNav=false,dark=false,className=''}:{children:ReactNode;noNav?:boolean;dark?:boolean;className?:string}){
  return <main className={`app-shell ${dark?'dark-page':''} ${className}`}>{children}{!noNav&&<BottomNav/>}</main>;
}

function Progress({value}:{value:number}){return <div className="progress"><i style={{width:`${value}%`}}/></div>}
function Thumb({screen='home',className=''}:{screen?:string;className?:string}){return <div className={`thumb ${className}`}><img src={refs[screen]} alt=""/></div>}

function GoalRow({goal}:{goal:Goal}) { return <div className="goal-row"><Thumb screen={goal.domainId==='cpa'?'cpa':goal.domainId==='fitness'?'fitness':'home'}/><div className="goal-info"><b>{goal.title}</b><span>{goal.description}</span><Progress value={goal.progress}/></div><strong>{goal.progress}%</strong></div> }

function Home(){
  const nav=useNavigate(); const goals=(useLiveQuery(()=>db.goals.bulkGet(['g1','g2','g3']),[])??[]).filter(Boolean) as Goal[];
  return <Shell className="home-page"><section className="home-hero" onClick={()=>nav('/goals')}><RefSlice screen="home" height={244}/></section>
    <section className="section"><div className="section-title"><h1>当前重点</h1><button onClick={()=>nav('/goals')}>全部 ›</button></div><div className="goal-card">{goals.map(g=><GoalRow key={g.id} goal={g}/>)}</div></section>
    <section className="section recent"><h1>最近人生</h1><div className="recent-grid">{[['home','晨跑 5 km','今天 07:30'],['fitness','力量训练','10月3日'],['cpa','CPA 学习','10月2日']].map(([s,t,d])=><button key={t} onClick={()=>nav(t.includes('CPA')?'/note/cpa':'/timeline')}><Thumb screen={s}/><b>{t}</b><span>{d}</span></button>)}</div></section>
  </Shell>;
}

function DomainTabs(){return <div className="domain-tabs">{['总览','记录','数据','知识','资源'].map((t,i)=><button className={i===0?'active':''} key={t}>{t}</button>)}</div>}
function Fitness(){return <Shell className="domain-page"><RefSlice screen="fitness" height={190}/><DomainTabs/><div className="page-pad">
  <article className="primary-card"><span>当前目标</span><h1>体脂降到 15%</h1><p>目标：2025年12月31日　68%</p></article>
  <div className="metric-grid">{[['体重','72.4 kg','↓ 1.6'],['体脂率','18.3%','↓ 2.1%'],['力量','+12%','近3个月']].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></article>)}</div>
  <h2>变化对比</h2><RefSlice screen="fitness" top={525} height={92} className="compare-reference"/>
  <h2>最近记录</h2><button className="latest-card"><Thumb screen="fitness"/><span><b>背部训练</b><small>今天 1小时20分钟 · 状态很好</small></span><Plus/></button>
  </div></Shell>}

function CPA(){return <Shell className="cpa-page"><RefSlice screen="cpa" height={204}/><DomainTabs/><div className="page-pad">
  <article className="count-card"><span>距离考试还有</span><div><b>136</b> 天</div><small>2027年2月17日</small><label>学习进度 <strong>42%</strong></label><Progress value={42}/></article>
  <div className="section-title"><h2>科目进度</h2><button>管理</button></div><div className="subject-grid">{[['会计',60],['审计',35],['财管',28],['税法',45]].map(([s,n])=><div key={s as string}>{s}<b>{n}%</b></div>)}</div>
  <div className="section-title"><h2>本周状态</h2><button>4/7 天</button></div><div className="week">{['一','二','三','四','五','六','日'].map((d,i)=><div key={d}><span className={i<4?'done':''}>{i<4?'✓':'·'}</span><small>{d}</small></div>)}</div>
  <div className="section-title"><h2>最近学习</h2><button>全部 ›</button></div><div className="learn-grid">{[['note','审计·第三章','32:18'],['fitness','税法知识点','图片'],['cpa','会计习题','18:42']].map(([s,t,b])=><article key={t}><Thumb screen={s}/><b>{t}</b><small>{b}</small></article>)}</div></div></Shell>}

function Knowledge(){
  const [scale,setScale]=useState(1); const [offset,setOffset]=useState({x:0,y:0}); const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
  const move=(e:ReactPointerEvent)=>{if(drag.current)setOffset({x:drag.current.ox+e.clientX-drag.current.x,y:drag.current.oy+e.clientY-drag.current.y})};
  return <Shell dark className="knowledge-page"><StatusBar dark/><header className="dark-header"><ArrowLeft/><h1>知识空间</h1><span/><button><Search/></button><button><Ellipsis/></button></header>
    <div className="knowledge-tabs">{['全部','健身','CPA','英语','生活'].map((x,i)=><button className={i===2?'active':''} key={x}>{x}</button>)}</div>
    <section className="graph" onWheel={(e:WheelEvent)=>setScale(Math.max(.7,Math.min(1.6,scale-e.deltaY*.001)))} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}} onPointerMove={move} onPointerUp={()=>drag.current=null}>
      <div className="graph-controls"><button onClick={()=>setScale(s=>Math.min(1.6,s+.1))}><ZoomIn/></button><button onClick={()=>setScale(s=>Math.max(.7,s-.1))}><ZoomOut/></button></div>
      <div className="graph-plane" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${scale})`}}><svg viewBox="0 0 393 360"><g stroke="#299565" strokeWidth="1.5" opacity=".8">{[[196,175,82,63],[196,175,292,58],[196,175,335,137],[196,175,312,252],[196,175,198,309],[196,175,86,273],[196,175,45,176]].map((p,i)=><line key={i} x1={p[0]} y1={p[1]} x2={p[2]} y2={p[3]}/>)}</g></svg>
        <GraphNode main x={196} y={175} label="CPA 考试" screen="cpa" count={42}/>{[['审计',82,63,'note',12],['会计',292,58,'fitness',18],['财管',335,137,'cpa',9],['税法',312,252,'note',7],['资料',198,309,'fitness',8],['真题',86,273,'home',24],['学习方法',45,176,'fitness',15]].map(([l,x,y,s,c])=><GraphNode key={l as string} x={x as number} y={y as number} label={l as string} screen={s as string} count={c as number}/>)}</div>
    </section><section className="dark-notes"><div className="section-title"><h2>相关笔记 <small>24</small></h2><button>全部 ›</button></div><div className="dark-card">{[['note','审计·第三章重点讲解','10月4日 20:00'],['fitness','会计分录练习','10月3日 19:20'],['cpa','税法知识点整理','10月2日 18:30']].map(x=><article key={x[1]}><Thumb screen={x[0]}/><span><b>{x[1]}</b><small>{x[2]}</small><em>#审计</em></span><ChevronRight/></article>)}</div></section></Shell>
}
function GraphNode({x,y,label,screen,count,main=false}:{x:number;y:number;label:string;screen:string;count:number;main?:boolean}){return <button className={`graph-node ${main?'main':''}`} style={{left:x,top:y}}><Thumb screen={screen}/><i>{count}</i><span>{label}</span></button>}

const timeline=[['今天','home','晨跑 5 km','早上的空气真好，感觉充满能量。','07:30 · 健身'],['10月3日','fitness','背部训练','状态很好，重量提升了。','19:20 · 健身'],['10月2日','cpa','CPA 学习 2 小时','完成了审计第三章的题。','20:00 · CPA'],['10月1日','home','和朋友吃饭','聊了很多，心情很好。','19:00 · 生活']];
function Timeline(){return <Shell className="timeline-page"><StatusBar/><h1 className="page-title">时间</h1><div className="filter-tabs">{['全部','经历','思想','情绪','里程碑'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><div className="timeline-list">{timeline.map((x,i)=><article key={x[2]}><time>{x[0]}</time><i/><Thumb screen={x[1]}/><div><b>{x[2]}</b><p>{x[3]}</p><small>{x[4]}</small></div></article>)}</div><button className="floating-add"><Plus/></button></Shell>}

function QuickCapture(){
  const nav=useNavigate(); const [type,setType]=useState('日记'),[text,setText]=useState(''),[selected,setSelected]=useState<string[]>(['学习','CPA']),[previews,setPreviews]=useState<{id:string;url:string;kind:string}[]>([]);
  const tags=(useLiveQuery(()=>db.tags.toArray(),[])??[]).sort((a,b)=>a.id.localeCompare(b.id)); const fileRef=useRef<HTMLInputElement>(null);
  const pick=async(e:ChangeEvent<HTMLInputElement>)=>{for(const file of Array.from(e.target.files??[])){const folder=file.type.startsWith('video')?'videos':file.type.startsWith('audio')?'audio':file.type.startsWith('image')?'images':'attachments';const kind:MediaRecord['kind']=folder==='videos'?'video':folder==='audio'?'audio':folder==='images'?'image':'file';const opfsPath=await saveMedia(file,folder);let url=URL.createObjectURL(file),thumbnailPath:string|undefined;if(kind==='video'){const b=await videoThumbnail(file);thumbnailPath=await saveThumbnail(b);url=URL.createObjectURL(b)}const id=crypto.randomUUID();await db.media.add({id,kind,opfsPath,thumbnailPath,mime:file.type||'application/octet-stream',size:file.size,createdAt:new Date().toISOString(),title:file.name});setPreviews(p=>[...p,{id,url,kind}]);}};
  const save=async()=>{if(text.trim()||previews.length){const now=new Date().toISOString();await db.entries.add({id:crypto.randomUUID(),content:text,createdAt:now,updatedAt:now,domainIds:[],goalIds:[],tags:selected,media:previews.map(p=>p.id),metrics:[],emotion:type==='情绪'?'记录':undefined});for(const t of selected){const found=await db.tags.where('name').equals(t).first();if(found)await db.tags.update(found.id,{count:found.count+1,lastUsedAt:now});else await db.tags.add({id:crypto.randomUUID(),name:t,count:1,lastUsedAt:now})}}nav('/')};
  const hash=text.match(/#([^\s#]*)$/)?.[1]??'';const suggestions=hash?tags.filter(t=>t.name.startsWith(hash)).slice(0,4):[];
  return <Shell noNav className="capture-page"><StatusBar/><header className="capture-header"><button onClick={()=>nav(-1)}><ArrowLeft/></button><h1>快速记录</h1><button onClick={save}>完成</button></header><div className="capture-body">
    <div className="capture-types">{['日记','灵感','想法','情绪','待办'].map(x=><button className={x===type?'active':''} onClick={()=>setType(x)} key={x}>{x}</button>)}</div>
    <article className="template-choice"><small>使用模板（可选）</small><div><span><b>空白记录</b><em>自由记录，不受模板限制</em></span><button onClick={()=>nav('/templates')}>选择模板</button></div></article>
    <textarea aria-label="记录内容" placeholder="此刻的想法……" value={text} onChange={e=>setText(e.target.value)}/>{suggestions.length>0&&<div className="tag-suggestions">{suggestions.map(t=><button key={t.id} onClick={()=>{setSelected(s=>Array.from(new Set([...s,t.name])));setText(v=>v.replace(/#[^\s#]*$/,'#'+t.name+' '))}}>#{t.name}</button>)}</div>}
    {previews.length>0&&<div className="media-previews">{previews.map((p,i)=><div key={i}><img src={p.url}/>{p.kind==='videos'&&<Play/>}</div>)}</div>}
    <input hidden multiple ref={fileRef} type="file" onChange={pick}/><div className="media-actions">{[[ImageIcon,'图片','image/*'],[Video,'视频','video/*'],[Mic,'录音','audio/*'],[Paperclip,'附件','*/*']].map(([Icon,label,accept])=><button key={label as string} onClick={()=>{if(fileRef.current){fileRef.current.accept=accept as string;fileRef.current.click()}}}>{typeof Icon!=='string'&&<Icon/>}<span>{label as string}</span></button>)}</div>
    <div className="section-title"><h2>标签</h2><button onClick={()=>nav('/tags')}>管理 ›</button></div><article className="tag-picker"><small>已选择</small><div>{selected.map(t=><button className="selected" key={t} onClick={()=>setSelected(s=>s.filter(x=>x!==t))}>#{t} ×</button>)}<button onClick={()=>{const n=prompt('新标签');if(n)setSelected(s=>[...s,n.replace(/^#/,'')])}}>＋ 添加</button></div><small>最近使用</small><div>{tags.slice(0,8).map(t=><button key={t.id} className={selected.includes(t.name)?'selected':''} onClick={()=>setSelected(s=>s.includes(t.name)?s.filter(x=>x!==t.name):[...s,t.name])}>#{t.name}</button>)}</div></article>
    <h2>今天的我</h2><article className="emotion-card">平静 · 专注 · 正在积累</article>
  </div></Shell>;
}

function Goals(){const goals=(useLiveQuery(()=>db.goals.toArray(),[])??[]).sort((a,b)=>a.id.localeCompare(b.id)); const [tab,setTab]=useState('active'); const shown=goals.filter(g=>tab==='done'?g.status==='done':tab==='paused'?g.status==='paused':g.status!=='done'&&g.status!=='paused');return <Shell className="goals-page"><StatusBar/><h1 className="page-title">我的目标</h1><div className="goal-tabs">{[['active','进行中'],['done','已完成'],['paused','已暂停']].map(([k,t])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t}</button>)}</div><div className="goal-card goals-list">{shown.map(g=><GoalRow key={g.id} goal={g}/>)}</div><button className="floating-add" onClick={async()=>{const title=prompt('目标名称');if(title){const n=new Date().toISOString();await db.goals.add({id:crypto.randomUUID(),title,description:'新的目标',status:'active',progress:0,createdAt:n,updatedAt:n})}}}><Plus/></button></Shell>}

function NoteDetail(){const nav=useNavigate();return <Shell noNav className="note-page"><StatusBar/><header className="note-header"><button onClick={()=>nav(-1)}><ArrowLeft/></button><h1>笔记详情</h1><span/><button><Share2/></button><button><Ellipsis/></button></header><RefSlice screen="note" top={85} height={171}/><div className="note-body"><h1>审计 · 第三章重点讲解</h1><p className="muted">2026年10月4日 · 20:00 · CPA</p><div className="chips"><span>#审计</span><span>#第三章</span><span>#重点</span><button>＋ 标签</button></div><article className="used-template"><span><small>使用模板</small><b>学习笔记模板</b></span><button>更换 ›</button></article><div className="section-title"><h2>笔记内容</h2><button>编辑</button></div><article className="note-content"><h3>🎯 本次目标</h3><p>• 理解审计风险评估流程<br/>• 掌握重要概念和例题</p><h3>📝 重点内容</h3><p>1. 风险评估的基本流程<br/>2. 重要性水平的确定方法<br/>3. 重大错报风险识别</p><h3>💡 我的理解</h3><p>这一章真正重要的是理解风险从哪里来，以及如何通过程序识别与应对。</p></article></div></Shell>}

function Profile(){const nav=useNavigate(); const entries=useLiveQuery(()=>db.entries.count(),[])??0; const actions:Array<[typeof BarChart3,string,string,()=>void|Promise<void>]>=[[BarChart3,'数据统计','查看长期变化与对比',()=>nav('/goals')],[TagIcon,'标签管理','整理、合并和复用标签',()=>nav('/tags')],[Notebook,'模板管理','新建、编辑、复制记录模板',()=>nav('/templates')],[Share2,'备份与恢复','导出 / 导入全部本地数据',()=>{confirm('确定：导出备份\n取消：选择备份文件恢复')?backup():restoreBackup()}],[Settings,'主题设置','外观、字体与布局',()=>{document.documentElement.classList.toggle('high-contrast')}],[CircleDot,'关于 MYM Life','版本与说明',()=>{alert('MYM Life 1.0 · 完全本地')}]];return <Shell className="profile-page"><StatusBar/><RefSlice screen="profile" top={34} height={151}/><div className="avatar"><Thumb screen="home"/></div><h1>更好的自己</h1><p>持续成长 · 保持清醒</p><div className="stats"><b>{128+entries}<small>记录</small></b><b>6<small>进行中目标</small></b><b>42<small>常用标签</small></b></div><div className="profile-actions">{actions.map(([Icon,t,d,fn])=><button key={t} onClick={fn}><Icon/><span><b>{t}</b><small>{d}</small></span><ChevronRight/></button>)}</div></Shell>}
async function backup(){const data={version:1,exportedAt:new Date().toISOString(),lines:await db.lines.toArray(),goals:await db.goals.toArray(),entries:await db.entries.toArray(),tags:await db.tags.toArray(),templates:await db.templates.toArray()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`mym-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function restoreBackup(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.version!==1)throw new Error('不支持的备份版本');await db.transaction('rw',[db.lines,db.goals,db.entries,db.tags,db.templates],async()=>{await Promise.all([db.lines.clear(),db.goals.clear(),db.entries.clear(),db.tags.clear(),db.templates.clear()]);await db.lines.bulkAdd(data.lines??[]);await db.goals.bulkAdd(data.goals??[]);await db.entries.bulkAdd(data.entries??[]);await db.tags.bulkAdd(data.tags??[]);await db.templates.bulkAdd(data.templates??[])});alert('恢复完成')}catch(error){alert(`恢复失败：${error instanceof Error?error.message:'文件无效'}`)}};input.click()}

const iconMap:Record<string,typeof FileText>={FileText,Notebook,BookOpen,Play,Users,Briefcase:BriefcaseBusiness,CircleDot,RefreshCw};
function Templates(){const nav=useNavigate(); const templates=useLiveQuery(()=>db.templates.orderBy('order').toArray(),[])??[]; const add=async()=>{const title=prompt('模板名称');if(title)await db.templates.add({id:crypto.randomUUID(),title,description:'自定义模板',icon:'FileText',fields:[],sections:[],defaultTags:[],order:templates.length})};return <Shell noNav className="manage-page templates-page"><StatusBar/><header><button onClick={()=>nav(-1)}><ArrowLeft/></button><h1>模板管理</h1><button onClick={add}><Plus/></button></header><div className="manage-pad"><div className="capture-types">{['全部','学习','工作','生活','健身'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><label className="searchbox"><Search/><input placeholder="搜索模板"/></label><div className="template-grid">{templates.map(t=><TemplateCard key={t.id} t={t} onUse={()=>nav('/capture')}/>)}</div><button className="new-template" onClick={add}><Plus/> 新建自定义模板</button></div></Shell>}
function TemplateCard({t,onUse}:{t:Template;onUse:()=>void}){const Icon=iconMap[t.icon]??FileText;return <article><div className="template-icon"><Icon/></div><h2>{t.title}</h2><p>{t.description}</p><footer><button onClick={onUse}>使用</button><span><button onClick={()=>{const name=prompt('重命名',t.title);if(name)db.templates.update(t.id,{title:name})}}>编辑</button> · <button onClick={async()=>db.templates.add({...t,id:crypto.randomUUID(),title:`${t.title} 副本`,order:t.order+1})}>复制</button></span></footer></article>}

function Tags(){const nav=useNavigate(); const tags=(useLiveQuery(()=>db.tags.toArray(),[])??[]).sort((a,b)=>a.id.localeCompare(b.id)); const [q,setQ]=useState('');const add=async()=>{const name=prompt('新标签');if(name)await db.tags.add({id:crypto.randomUUID(),name:name.replace(/^#/,''),count:0,lastUsedAt:new Date().toISOString()})}; const menu=async(id:string,name:string)=>{const action=prompt('输入：重命名 / 合并 / 删除');if(action==='删除'){await db.tags.delete(id);const entries=await db.entries.where('tags').equals(name).toArray();await Promise.all(entries.map(e=>db.entries.update(e.id,{tags:e.tags.filter(t=>t!==name)})))}else if(action==='重命名'){const n=prompt('新名称',name);if(n)await db.tags.update(id,{name:n.replace(/^#/,'')})}else if(action==='合并'){const n=prompt('合并到标签名称');if(n){const entries=await db.entries.where('tags').equals(name).toArray();await Promise.all(entries.map(e=>db.entries.update(e.id,{tags:Array.from(new Set(e.tags.map(t=>t===name?n:t)))})));await db.tags.delete(id)}}}; return <Shell noNav className="manage-page tags-page"><StatusBar/><header><button onClick={()=>nav(-1)}><ArrowLeft/></button><h1>标签管理</h1><button onClick={add}><Plus/></button></header><div className="manage-pad"><label className="searchbox"><Search/><input placeholder="搜索标签" value={q} onChange={e=>setQ(e.target.value)}/></label><article className="tag-rule"><small>标签规则</small><p>用过的标签会自动保留。记录时可以直接点选；支持重命名、合并和删除，不会限制你创建新的标签。</p></article><div className="section-title"><h2>常用标签</h2><button>按使用次数</button></div><div className="tag-list">{tags.filter(t=>t.name.includes(q.replace(/^#/,''))).map(t=><div key={t.id}><b>#{t.name}</b><span>{t.count} 条记录</span><button onClick={()=>menu(t.id,t.name)}><MoreHorizontal/></button></div>)}</div></div></Shell>}

function Overlay(){const location=useLocation();const [opacity,setOpacity]=useState(.5);const enabled=new URLSearchParams(location.search).get('debugOverlay')==='1';if(!enabled)return null;const key=location.pathname.startsWith('/note')?'note':screens[location.pathname]??'home';return <><img className="debug-overlay" style={{opacity}} src={refs[key]}/><div className="overlay-control"><label>Overlay {Math.round(opacity*100)}%</label><input type="range" min="0" max="1" step=".25" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></div></>}

export default function App(){useEffect(()=>{ensureSeedData()},[]);return <><Routes><Route path="/" element={<Home/>}/><Route path="/fitness" element={<Fitness/>}/><Route path="/cpa" element={<CPA/>}/><Route path="/knowledge" element={<Knowledge/>}/><Route path="/timeline" element={<Timeline/>}/><Route path="/capture" element={<QuickCapture/>}/><Route path="/goals" element={<Goals/>}/><Route path="/note/:id" element={<NoteDetail/>}/><Route path="/profile" element={<Profile/>}/><Route path="/templates" element={<Templates/>}/><Route path="/tags" element={<Tags/>}/></Routes><Overlay/></>}
